Merge r199 from trunk.

diff --git a/wgetpaste b/wgetpaste
--- a/wgetpaste
+++ b/wgetpaste
@@ -105,8 +105,10 @@ converttoraw() {
 	if [[ -n ${!regex} ]]; then
 		RAWURL=$(sed -e "${!regex}" <<< "$URL")
 		[[ -n $RAWURL ]] && return 0
+		echo "Convertion to raw url failed." >&2
+	else
+		echo "Raw download of pastes is not supported by $(getrecipient)." >&2
 	fi
-	echo "Raw download of pastes is not supported by $(getrecipient)." >&2
 	return 1
 }
 
